# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

email = "wirdatulamalia+31@gmail.com"
password = "Amalia.123"
username = "amaliawh31"

class TestRegisterGank():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registerGank(self):
    # Test name: Register Gank
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://ganknow.com/")
    # 2 | setWindowSize | 1440x900 | 
    self.driver.set_window_size(1440, 900)
    # 3 | click | css=.gank-btn:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".gank-btn:nth-child(2)").click()
    time.sleep(2)
    # 4 | click | id=login_email | 
    self.driver.find_element(By.ID, "login_email").click()
    # 5 | type | id=login_email | wirdatulamalia+12@gmail.com
    self.driver.find_element(By.ID, "login_email").send_keys(email)
    # 6 | click | id=login_password | 
    self.driver.find_element(By.ID, "login_password").click()
    # 7 | type | id=login_password | Amalia.123
    self.driver.find_element(By.ID, "login_password").send_keys(password)
    # 8 | click | css=.gank-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".gank-btn").click()
    time.sleep(2)
    # 10 | type | id=create-username_nickname | amaliawh12
    self.driver.find_element(By.ID, "create-username_nickname").send_keys(username)
    # 11 | click | css=.gank-btn-primary |  
    self.driver.find_element(By.CSS_SELECTOR, ".gank-btn-primary").click()
    time.sleep(2)
    # 12 | click | css=.user-type-container:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".user-type-container:nth-child(1)").click()
    # 13 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 14 | verifyText | css=.max-w-xs | Your account has been created! Please check your email inbox to verify your email before proceeding.
    assert self.driver.find_element(By.CSS_SELECTOR, ".max-w-xs").text == "Your account has been created! Please check your email inbox to verify your email before proceeding."
    # 15 | close |  | 
    self.driver.close()

class TestLoginGank():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginGank(self):
    # Test name: Login Gank
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://ganknow.com/")
    # 2 | setWindowSize | 1440x900 | 
    self.driver.set_window_size(1440, 900)
    # 3 | click | css=.gank-btn-ghost | 
    self.driver.find_element(By.CSS_SELECTOR, ".gank-btn-ghost").click()
    time.sleep(2)
    # 4 | click | id=login_email | 
    self.driver.find_element(By.ID, "login_email").click()
    # 5 | type | id=login_email | wirdatulamalia+22@gmail.com
    self.driver.find_element(By.ID, "login_email").send_keys(email)
    # 6 | click | id=login_password | 
    self.driver.find_element(By.ID, "login_password").click()
    # 7 | type | id=login_password | Amalia.123
    self.driver.find_element(By.ID, "login_password").send_keys(password)
    # 8 | click | css=.gank-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".gank-btn").click()
    time.sleep(7)

    # 12 | verifyText | css=.cursor-pointer > h3 | Beranda
    assert self.driver.find_element(By.CSS_SELECTOR, ".cursor-pointer > h3").text == "Beranda"
    # 13 | close |  | 
    self.driver.close()
  
